name: "Sphinx Build"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          submodules: true

      - name: Build
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "./"
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: "DocumentationHTML"
          path: _build/html/
 
