name: "Sphinx Build"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@main
        with:
          python-version: '3.10'
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Build
        run: |
          pip install -r requirements.txt
          make clean && make html
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: "DocumentationHTML"
          path: _build/html/
 
